# 3 hình tròn
bankinh = float(input("nhap ban kinh = "))
khoangcach = float(input("nhap khoang cach cac hinh tron = "))
import turtle
screen = turtle.Screen()
t = turtle.Turtle()
t.penup()
t.goto(0,-bankinh)
t.pendown()
t.circle(bankinh)
t.penup()
t.goto(0,-bankinh+khoangcach)
t.pendown()
t.circle(bankinh-khoangcach)
t.penup()
t.goto(0,-bankinh+(2*khoangcach))
t.pendown()
t.circle(bankinh-(2*khoangcach))
turtle.done()
